name: Mutation Tests

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'
  workflow_call:
    inputs:
      path:
        required: false
        default: src
        type: string

jobs:
  Mutation:
    name: Run Mutation Tests
    runs-on: [self-hosted, Linux]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            lfs: true
            fetch-depth: 0
            ref: ${{ github.head_ref }}
        
      - uses: actions/setup-dotnet@v3
        env:
          DOTNET_INSTALL_DIR: '%LocalAppData%/Microsoft/dotnet'
        with:
         dotnet-version: 6   
         cache: false

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Setup .NET Core SDK 
        run: |
          dotnet nuget add source https://jfrog.devops.nationalgrid.com/artifactory/api/nuget/v3/ng-grid-customer --name internal-jf --username ${{ secrets.JFROG_USERNAME }} --configfile ./src/nuget.config --password ${{ secrets.JFROG_PASSWORD }} --store-password-in-clear-text
          dotnet nuget update source internal-feed --source https://pkgs.dev.azure.com/NGRID/US-4750J-ADOProject-01/_packaging/uwp2/nuget/v3/index.json --username gitHub --configfile ./src/nuget.config --password ${{ secrets.AZURE_PACKAGE_TOKEN }} --store-password-in-clear-text        

      - name: Run tests
        run: cd ${{inputs.path}} && dotnet stryker -f ./stryker-config.json --version="${{ github.head_ref }}"
     
      - name: "Upload Stryker"
        uses: actions/upload-artifact@v3.1.2
        with:
          name: mutation
          path: |
            ./src/StrykerOutput

      - name: " Coverage Report Step Summary"
        if: ${{ always() }} # Upload even if tests don't pass testing threshold
        run: cat ./src/StrykerOutput/*/reports/mutation-report.md >> $GITHUB_STEP_SUMMARY

      - name: Get Number of Changed files
        id: git-diff
        run: |
          git status src
          echo "GitFiles=$(git status | grep stryker | wc -l | xargs)" >> $GITHUB_OUTPUT

      - if: ${{steps.git-diff.outputs.GitFiles  != '0' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/StrykerOutput/
          git commit -m "updated mutation baselines"
          git push