name: OpenAPI Gen

on:
  workflow_call:
    inputs:
      dll:
        required: true
        type: string
  

jobs:
  OpenApi:
    name: extract ${{ inputs.openapi_name }}
    runs-on: [self-hosted, Linux]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            lfs: true
            fetch-depth: 0
            ref: ${{ github.head_ref }}
        
      - uses: actions/setup-dotnet@v3
        env:
          DOTNET_INSTALL_DIR: '%LocalAppData%/Microsoft/dotnet'
        with:
         dotnet-version: 6   
         cache: false

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Setup .NET Core SDK 
        run: |
          dotnet nuget add source https://jfrog.devops.nationalgrid.com/artifactory/api/nuget/v3/ng-grid-customer --name internal-jf --username ${{ secrets.JFROG_USERNAME }} --configfile ./src/nuget.config --password ${{ secrets.JFROG_PASSWORD }} --store-password-in-clear-text
          dotnet nuget update source internal-feed --source https://pkgs.dev.azure.com/NGRID/US-4750J-ADOProject-01/_packaging/uwp2/nuget/v3/index.json --username gitHub --configfile ./src/nuget.config --password ${{ secrets.AZURE_PACKAGE_TOKEN }} --store-password-in-clear-text
          dotnet restore ./src

      - name: Copying Local Appsettings
        run: cp src/Api/appsettings.test.json src/Api/appsettings.json 

      - name: Build App
        run: dotnet build src

      - name: Generate All OpenAPI Specs
        run: sh <(curl https://tea.xyz) npx zx --install ./get-all-openapi.mjs --dll ${{ inputs.dll }}
   
      - name: Upload OpenAPI Specs
        uses: actions/upload-artifact@v3.1.2
        with:
          name: openapi
          path: |
            openapi

      - name: Get Number of Changed files
        id: git-diff
        run: |
          git status src
          echo "GitFiles=$(git status | grep openapi/ | wc -l | xargs)" >> $GITHUB_OUTPUT

      - if: ${{ steps.git-diff.outputs.GitFiles != '0' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add openapi/
          git commit -m "generated openapi specs"
          git push